import { AdminUserInfo } from "../../../typescript-types/db.types";

export const cr: AdminUserInfo[] = [
  {
    isActive: true,
    firstName: "Lynne",
    lastName: "Conley",
    location: "Florence",
    role: "user",
    grade: "senior",
    job: "QA",
    email: "elisabethhorne@danja.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Hogan",
    lastName: "Dominguez",
    location: "Nettie",
    role: "admin",
    grade: "junior",
    job: "QA",
    email: "ramseyparker@pholio.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Angelita",
    lastName: "Guy",
    location: "Zortman",
    role: "user",
    grade: "senior",
    job: "QA",
    email: "bushewing@zillactic.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Manning",
    lastName: "Mckay",
    location: "Fulford",
    role: "admin",
    grade: "middle",
    job: "QA",
    email: "juanaodom@rodeomad.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Galloway",
    lastName: "Nguyen",
    location: "Grimsley",
    role: "admin",
    grade: "middle",
    job: "UX",
    email: "duffyflowers@combot.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Desiree",
    lastName: "Abbott",
    location: "Bentonville",
    role: "user",
    grade: "junior",
    job: "QA",
    email: "altarose@roughies.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Joni",
    lastName: "Boyd",
    location: "Jacksonwald",
    role: "user",
    grade: "senior",
    job: "QA",
    email: "inayang@ecratic.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Bradley",
    lastName: "Cote",
    location: "Rockbridge",
    role: "admin",
    grade: "middle",
    job: "Dev",
    email: "carissawiley@ultrasure.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Nellie",
    lastName: "Lawson",
    location: "Chilton",
    role: "admin",
    grade: "junior",
    job: "QA",
    email: "elenapacheco@orbixtar.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Hollie",
    lastName: "Hurst",
    location: "Staples",
    role: "user",
    grade: "middle",
    job: "Dev",
    email: "candiceparrish@unisure.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Reba",
    lastName: "Mckee",
    location: "Groton",
    role: "user",
    grade: "middle",
    job: "Dev",
    email: "meyersrodgers@zeam.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Rowena",
    lastName: "Nicholson",
    location: "Harrodsburg",
    role: "admin",
    grade: "middle",
    job: "UX",
    email: "murraysweeney@otherside.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Suzette",
    lastName: "Greene",
    location: "Esmont",
    role: "user",
    grade: "senior",
    job: "Dev",
    email: "hatfieldacosta@stelaecor.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Small",
    lastName: "Welch",
    location: "Nile",
    role: "admin",
    grade: "senior",
    job: "QA",
    email: "toddcole@geeky.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Lupe",
    lastName: "Fletcher",
    location: "Williamson",
    role: "user",
    grade: "junior",
    job: "Dev",
    email: "darlacollins@xinware.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Buckley",
    lastName: "Fowler",
    location: "Rockhill",
    role: "user",
    grade: "senior",
    job: "UX",
    email: "youngmartin@springbee.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Mara",
    lastName: "West",
    location: "Yorklyn",
    role: "user",
    grade: "junior",
    job: "Dev",
    email: "billiepayne@egypto.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Sloan",
    lastName: "Russell",
    location: "Glendale",
    role: "admin",
    grade: "middle",
    job: "QA",
    email: "juliannebarrera@remotion.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Cynthia",
    lastName: "Solis",
    location: "Gordon",
    role: "admin",
    grade: "middle",
    job: "UX",
    email: "lloydfranks@comtent.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Mercado",
    lastName: "Mendoza",
    location: "Rote",
    role: "user",
    grade: "junior",
    job: "Dev",
    email: "levinefisher@magnina.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Alisha",
    lastName: "Mcmahon",
    location: "Caspar",
    role: "user",
    grade: "middle",
    job: "UX",
    email: "figueroafreeman@recritube.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Wilkinson",
    lastName: "Sawyer",
    location: "Kylertown",
    role: "admin",
    grade: "senior",
    job: "Dev",
    email: "gloriaweaver@uni.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Maryellen",
    lastName: "Browning",
    location: "Caron",
    role: "admin",
    grade: "senior",
    job: "UX",
    email: "jerriburris@balooba.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Louella",
    lastName: "Madden",
    location: "Sisquoc",
    role: "admin",
    grade: "senior",
    job: "QA",
    email: "hudsonwhite@xelegyl.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Rhoda",
    lastName: "Hawkins",
    location: "Gardiner",
    role: "user",
    grade: "junior",
    job: "Dev",
    email: "estradaaguirre@dyno.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Bauer",
    lastName: "Matthews",
    location: "Camptown",
    role: "admin",
    grade: "junior",
    job: "QA",
    email: "janettewaters@suremax.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Beasley",
    lastName: "Nash",
    location: "Dupuyer",
    role: "user",
    grade: "senior",
    job: "UX",
    email: "sheltonmoss@solgan.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Ball",
    lastName: "Barton",
    location: "Yorklyn",
    role: "user",
    grade: "middle",
    job: "Dev",
    email: "estertodd@calcula.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Rowena",
    lastName: "Meyers",
    location: "Brethren",
    role: "admin",
    grade: "middle",
    job: "Dev",
    email: "coleenkemp@pyramis.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Helena",
    lastName: "Moody",
    location: "Summerset",
    role: "admin",
    grade: "middle",
    job: "UX",
    email: "normancooley@progenex.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Nancy",
    lastName: "Christensen",
    location: "Wescosville",
    role: "admin",
    grade: "junior",
    job: "Dev",
    email: "lynchstuart@jetsilk.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Miranda",
    lastName: "Lang",
    location: "Foscoe",
    role: "user",
    grade: "junior",
    job: "Dev",
    email: "mckinneylindsay@extragene.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Doris",
    lastName: "Simon",
    location: "Saranap",
    role: "user",
    grade: "senior",
    job: "Dev",
    email: "dellastanton@tourmania.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Maynard",
    lastName: "Huffman",
    location: "Dante",
    role: "admin",
    grade: "middle",
    job: "UX",
    email: "earlenedawson@concility.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Earnestine",
    lastName: "Dickerson",
    location: "Summertown",
    role: "user",
    grade: "senior",
    job: "Dev",
    email: "gabrielamendez@austech.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Jaime",
    lastName: "Anthony",
    location: "Dyckesville",
    role: "user",
    grade: "senior",
    job: "QA",
    email: "mccoymerrill@insource.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Mcleod",
    lastName: "Griffith",
    location: "Conway",
    role: "user",
    grade: "junior",
    job: "QA",
    email: "juliefowler@toyletry.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Pierce",
    lastName: "Alston",
    location: "Riegelwood",
    role: "admin",
    grade: "middle",
    job: "UX",
    email: "lynnettefoley@dogspa.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Jill",
    lastName: "Rutledge",
    location: "Farmington",
    role: "admin",
    grade: "middle",
    job: "Dev",
    email: "simonenorris@manufact.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Tate",
    lastName: "Butler",
    location: "Harleigh",
    role: "user",
    grade: "middle",
    job: "QA",
    email: "lowerymontgomery@hotcakes.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Lillie",
    lastName: "Gamble",
    location: "Hayes",
    role: "user",
    grade: "middle",
    job: "Dev",
    email: "shelleylane@eclipto.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Pearl",
    lastName: "Mccarty",
    location: "Taycheedah",
    role: "user",
    grade: "middle",
    job: "UX",
    email: "tracisweet@signity.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Lila",
    lastName: "Burris",
    location: "Mappsville",
    role: "admin",
    grade: "middle",
    job: "Dev",
    email: "stephaniesmall@extragen.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Maggie",
    lastName: "Keith",
    location: "Blanco",
    role: "admin",
    grade: "middle",
    job: "UX",
    email: "triciaphelps@mondicil.com",
    project: "Project3",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Holland",
    lastName: "Hays",
    location: "Chautauqua",
    role: "admin",
    grade: "senior",
    job: "Dev",
    email: "rowlandbenjamin@paragonia.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: false,
    firstName: "Lorraine",
    lastName: "Stevenson",
    location: "Accoville",
    role: "user",
    grade: "senior",
    job: "QA",
    email: "georginacook@equitax.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Malone",
    lastName: "Munoz",
    location: "Gwynn",
    role: "user",
    grade: "junior",
    job: "QA",
    email: "vickieblanchard@letpro.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Moses",
    lastName: "Molina",
    location: "Dana",
    role: "user",
    grade: "middle",
    job: "Dev",
    email: "jennabarrett@minga.com",
    project: "Project2",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Marva",
    lastName: "Mcclain",
    location: "Guilford",
    role: "user",
    grade: "junior",
    job: "QA",
    email: "conwayramos@ecrater.com",
    project: "Project1",
    departmentID: "",
  },
  {
    isActive: true,
    firstName: "Marlene",
    lastName: "Bowen",
    location: "Waterloo",
    role: "admin",
    grade: "middle",
    job: "QA",
    email: "jeanhensley@capscreen.com",
    project: "Project1",
    departmentID: "",
  },
];
