FROM node:16.13.1 as build
WORKDIR /app
COPY /package.json .
RUN npm install
COPY . .
ARG REACT_APP_BACKEND_BASE_URL

ENV REACT_APP_BACKEND_BASE_URL=$REACT_APP_BACKEND_BASE_URL

RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html