name: Chromatic (Storybook)
on:
  push:
    branches:
      - main

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install packages global
        working-directory: ./
        run: npm ci

      - name: install packages app
        working-directory: ./app
        run: npm ci

      - name: install packages functions
        working-directory: ./functions
        run: npm ci

      - name: Publish to Chromatic
        id: storybook
        uses: chromaui/action@v1
        with:
          workingDir: ./app
          exitZeroOnChanges: true
          autoAcceptChanges: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
