name: Chromatic (Storybook)
on:
  push:
    branches:
      - main

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
                
      - name: install all packages
        run: npm run all-install

      - name: Publish to Chromatic
        id: storybook
        uses: chromaui/action@v1
        with:
          workingDir: ./app
          exitZeroOnChanges: true
          autoAcceptChanges: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
