name: Lint on merge
"on":
  push:
    branches:
      - main

jobs:
  run-linters:
    name: linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install all packages
        run: npm run all-install

      - name: install packages global
        working-directory: ./
        run: npm ci

      - name: install packages app
        working-directory: ./app
        run: npm ci

      - name: install packages functions
        working-directory: ./functions
        run: npm ci

      - name: install packages ts
        working-directory: ./typescript-types
        run: npm ci

      - name: running linters app
        working-directory: ./app
        run: npm run lint

      - name: running linters functions
        working-directory: ./functions
        run: npm run lint
